=== FloFloDht/Projet-DPR/recettes.dtd
<!ELEMENT Recettes (CategoriePlat*, produits*, Ingredients*, Auteurs*)* >
<!ELEMENT recettes (Recette+) >

<!ELEMENT Recette (Titre, Resume, Photo, DatePublication, Difficulte, ref-ingrédient+, NbrePersonne, TmpsPreparation, TmpsCuisson?, TmpsRepos?, DescriptionPreparation, NoteInternautes, ref-auteur)* >
<!ELEMENT Titre ( #PCDATA) >
<!ELEMENT Resume (#PCDATA) >
<!ELEMENT Photo EMPTY >
<!ELEMENT DatePublication (#PCDATA) >
<!ELEMENT Difficulte (#PCDATA) >
<!ELEMENT ref-ingrédient EMPTY>
<!ELEMENT NbrePersonne (#PCDATA) >
<!ELEMENT TmpsPreparation (#PCDATA) >
<!ELEMENT TmpsCuisson (#PCDATA) > <!--0 ou 1-->
<!ELEMENT TmpsRepos (#PCDATA) > <!--0 ou 1-->
<!ELEMENT DescriptionPreparation (#PCDATA) >
<!ELEMENT NoteInternautes (#PCDATA) > <!--0 a n-->
<!ELEMENT ref-auteur EMPTY >

<!ELEMENT Ingredients (Ingredient+)>
<!ELEMENT Ingredient (Nom, ApportNutritif, ApportEnergetique, Saison, Description, idRec, idProd)>
<!ELEMENT Nom (#PCDATA) >
<!ELEMENT ApportNutritif (#PCDATA) >
<!ELEMENT ApportEnergetique (#PCDATA) >
<!ELEMENT Saison (#PCDATA) >
<!ELEMENT Description (#PCDATA) >
<!ELEMENT idRec EMPTY >
<!ELEMENT idProd EMPTY >

<!ELEMENT Auteurs (Auteur*) >
<!ELEMENT Auteur (nom, ref-recette, age?, pays, sexe?, bio?)>
<!ELEMENT nom (#PCDATA) >
<!ELEMENT ref-recette EMPTY >
<!ELEMENT age (#PCDATA) >
<!ELEMENT pays (#PCDATA) >
<!ELEMENT sexe (#PCDATA) >
<!ELEMENT bio (#PCDATA) >

<!ELEMENT CategoriePlat (Name, Desc, SousCategoriePlat)>
<!ELEMENT Name (#PCDATA) >
<!ELEMENT Desc (#PCDATA) >

<!ELEMENT SousCategoriePlat (name, desc, recettes) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT desc (#PCDATA) >

<!ELEMENT produits (produit*)>
<!ELEMENT produit (nomProduit)>
<!ELEMENT nomProduit (#PCDATA) >

<!ATTLIST Recette identifiant ID #REQUIRED>
<!ATTLIST Auteur id ID #REQUIRED>
<!ATTLIST ref-recette ref IDREF #REQUIRED>
<!ATTLIST idRec ref IDREF #REQUIRED>
<!ATTLIST ref-auteur ref IDREF #REQUIRED>
<!ATTLIST Ingredient id ID #REQUIRED>
<!ATTLIST ref-ingrédient ref IDREF #REQUIRED>
<!ATTLIST produit id ID #REQUIRED>
<!ATTLIST idProd ref IDREF #REQUIRED>

=== FloFloDht/Projet-DPR/recettes.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Recettes SYSTEM "recettes.dtd">

<Recettes>
    <CategoriePlat>
        <nom>Entrée</nom>
        <description>Les entrées</description>
        <SousCategoriePlat>
            <nom>Entrée chaudes</nom>
            <description>les entrées de types chauds</description>
            <recettes>
                <Recette identifiant="oeuf">
                    <Titre>Œufs cocotte avocat et jambon cru Aoste</Titre>
                    <Resume>Un œuf cocotte cuit dans un avocat: original, n’est-ce pas? Voici une recette originale, très facile à préparer et qui impressionnera vos convives.</Resume>
                    <Photo></Photo>
                    <DatePublication>c'est pas écrit</DatePublication>
                    <Difficulte>1</Difficulte>
                    <ref-ingrédient ref="sel"/>
                    <ref-ingrédient ref="poivre"/>
                    <NbrePersonne>4</NbrePersonne>
                    <TmpsPreparation>10 min</TmpsPreparation>
                    <TmpsCuisson>20 min</TmpsCuisson>
                    <DescriptionPreparation>1. Taillez les avocats en deux et ôtez le noyau. Assaisonnez (sel, poivre) puis badigeonnez les avocats d’huile d’olive avec un pinceau.

                        2. Déposez une demie tranche de jambon cru Aoste puis remplissez l’intérieur de l’avocat avec du blanc d’œuf et une petite cuillère à café de crème fraîche. Gardez les jaunes dans des petits ramequins individuels au réfrigérateur.

                        3. Enfournez les avocats garnis 15 minutes à 180 °C jusqu’à ce que le blanc soit presque cuit. Ajoutez ensuite les jaunes d’œufs. Poursuivez la cuisson 5 minutes.

                        4.Terminez en arrosant d’un petit filet d’huile d’olive et de ciboulette hachée.

                        Dégustez bien chaud !</DescriptionPreparation>
                    <NoteInternautes>non notée</NoteInternautes>
                    <ref-auteur ref="Aoste"/>
                </Recette>
            </recettes>
        </SousCategoriePlat>
    </CategoriePlat>



    <Auteurs>
        <Auteur id="Aoste">
            <nom>Aoste</nom>
            <ref-recette ref="oeuf"/>
            <pays>France</pays>
        </Auteur>
        <Auteur id="Tombini">
            <nom>Marie Tombini</nom>
            <ref-recette ref="oeuf"/>
            <pays>France</pays>
        </Auteur>
    </Auteurs>

    <produits>
        <produit id="autres">
            <nom>autres</nom>
        </produit>
    </produits>

    <Ingredients>
        <Ingredient id="sel">
            <nom>Sel</nom>
            <ApportNutritif>je sais pas</ApportNutritif>
            <ApportEnergetique>je sais pas</ApportEnergetique>
            <Saison>je sais pas</Saison>
            <description>je sais pas</description>
            <idRec ref="oeuf"/>
            <idProd ref="autres"/>
        </Ingredient>
        <Ingredient id="poivre">
            <nom>Poivre</nom>
            <ApportNutritif>je sais pas</ApportNutritif>
            <ApportEnergetique>je sais pas</ApportEnergetique>
            <Saison>je sais pas</Saison>
            <description>je sais pas</description>
            <idRec ref="oeuf"/>
            <idProd ref="autres"/>
        </Ingredient>
    </Ingredients>
</Recettes>
